// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mottu.Api.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Mottu.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927172109_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mottu.Api.Models.Filial", b =>
                {
                    b.Property<int>("FilialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilialId"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("FilialId");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("Mottu.Api.Models.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizacaoId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("MotoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LocalizacaoId");

                    b.HasIndex("MotoId");

                    b.HasIndex("SensorId");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("Mottu.Api.Models.Moto", b =>
                {
                    b.Property<int>("MotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoId"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("MotoId");

                    b.HasIndex("PatioId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Mottu.Api.Models.Patio", b =>
                {
                    b.Property<int>("PatioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatioId"));

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomePatio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("PatioId");

                    b.HasIndex("FilialId");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Mottu.Api.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("SensorId");

                    b.HasIndex("PatioId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("Mottu.Api.Models.Localizacao", b =>
                {
                    b.HasOne("Mottu.Api.Models.Moto", "Moto")
                        .WithMany("Localizacoes")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mottu.Api.Models.Sensor", "Sensor")
                        .WithMany("Localizacoes")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Moto");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Mottu.Api.Models.Moto", b =>
                {
                    b.HasOne("Mottu.Api.Models.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Mottu.Api.Models.Patio", b =>
                {
                    b.HasOne("Mottu.Api.Models.Filial", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Mottu.Api.Models.Sensor", b =>
                {
                    b.HasOne("Mottu.Api.Models.Patio", "Patio")
                        .WithMany("Sensores")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Mottu.Api.Models.Filial", b =>
                {
                    b.Navigation("Patios");
                });

            modelBuilder.Entity("Mottu.Api.Models.Moto", b =>
                {
                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("Mottu.Api.Models.Patio", b =>
                {
                    b.Navigation("Motos");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Mottu.Api.Models.Sensor", b =>
                {
                    b.Navigation("Localizacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
